#!/bin/sh
y#xrandr --output eDP-1 --scale-from 2016x1260
if [ "$(hostname)" = 'asahibook' ]; then
    xrandr --output eDP-1 --dpi 144
fi;

# Set up monitors with specific workspaces
if xrandr --query | grep "DP-1" | grep -v "eDP-1" | grep -q " connected "; then
    bspc monitor DP-1 -d "(first)" "(second)" "(third)"
    bspc monitor eDP-1 -d  "(fourth)" "(fifth)"
else
    bspc monitor -d "(first)" "(second)" "(third)" "(fourth)" "(fifth)"
fi

bspc config border_width 1
bspc config focused_border_color \#ffffff
#bspc config normal_border_color \#000000
bspc config normal_border_color \#ffffff
bspc config window_gap 0
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc rule -a brave desktop=^3
bspc rule -a emacs desktop=^1
bspc rule -a ghostty desktop=^2
picom --config ~/.config/picom/picom.conf &
dunst --config ~/.config/dunst/dunstrc &
feh --bg-scale ~/.config/wallpapers/wallpaper-10.jpg &
bash ~/.bin/battery.sh --daemon &
#polybar -c ~/.config/polybar/config.ini top &
emacs --daemon --eval "(progn (select-frame (make-frame-on-display \":0\")) (make-frame-invisible))" &
sxhkd &
