#!/bin/sh
#xrandr --output eDP-1 --scale-from 2016x1260

if [ "$(hostname)" = 'asahibook' ]; then
    xrandr --output eDP-1 --dpi 144
fi;

bspc monitor -d Hollow Thorne Grimoire Abyss Nocturne

bspc config border_width 5
bspc config focused_border_color \#a6e3a1
bspc config normal_border_color \#C68689
bspc config window_gap 15
bspc config split_ratio 0.60
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc rule -a Brave desktop=^3
bspc rule -a Emacs desktop=^1
bspc rule -a Ghostty desktop=^2

# killall -q polybar

# while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# polybar top &

# Reserve space on the left for Eww bar
#bspc config left_padding 30

# Eww bar: sticky, below all windows, and no border
# bspc rule -a Eww:bar state=floating layer=below sticky=on border=off

# # Start Eww bar
# eww daemon &
# sleep 0.5
# eww open bar

picom --config ~/.config/picom/picom.conf &
dunst --config ~/.config/dunst/dunstrc &
#feh --bg-scale ~/.config/wallpapers/gradient.png &
feh --bg-scale ~/.config/wallpapers/galaxy-plant.jpeg &
bash ~/.bin/battery.sh --daemon &

emacs
