#!/bin/sh

bspc monitor -d Hollow Thorne Grimoire Abyss Nocturne

bspc config border_width 10
bspc config focused_border_color \#a6e3a1
bspc config normal_border_color \#a6e3a1
bspc config window_gap 0
bspc config split_ratio 0.6
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc rule -a Firefox desktop=^3

killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch the bar
polybar top &
picom --experimental-backends --config ~/.config/picom/picom.conf &

