backend = "glx";
vsync = true;
shadow = true;
shadow-radius = 01;          # 0 means no blur, so it's solid
shadow-opacity = 1.0;       # full opacity (solid)
shadow-offset-x = 15;      # adjust horizontal position
shadow-offset-y = 15;      # adjust vertical position
shadow-color = "#000000";   # pure black shadow

fading = true;
fade-in-step = 0;
fade-out-step = 0;
inactive-opacity = 0.9;   # unfocused windows
active-opacity = 1.0;     # focused window
frame-opacity = 0.9;
inactive-opacity-override = false;

corner-radius = 20;
rounded-corners-exclude = [
  "window_type = 'dock'",   # polybar
  "class_g = 'Polybar'",
  "class_g = 'polybar'",	
  "class_g = 'Dmenu'",
  "class_g = 'dmenu'",	
  "window_type = 'desktop'"
];
shadow-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'eww-bar'",
  "class_g = 'dmenu'",
  "class_g = 'dunst'",
  "name = 'Notification'"
];

blur:
{
  method = "dual_kawase";
  strength = 10;
};

