#!/bin/sh

# Set wallpaper
#feh --bg-scale /path/to/your/wallpaper.jpg

# Launch sxhkd for keybindings
# sxhkd &

xset s blank
xset s 300
xset dpms 600 900 1200
xautolock -detectsleep -time 20 -locker "$HOME/.local/bin/lock" &
exec bspwm
